CREATE TABLE CAR(
  CAR_ID BIGSERIAL PRIMARY KEY,
  LICENSE_PLATE_NUMBER CHAR(12) NOT NULL UNIQUE
);

CREATE TABLE APIUSER(
  USER_ID BIGSERIAL PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64),
  ADDRESS VARCHAR(64),
  COUNTRY VARCHAR(32),
  STATE VARCHAR(12),
  PHONE_NUMBER VARCHAR(24)
);

CREATE TABLE RESERVATION(
  RESERVATION_ID BIGSERIAL PRIMARY KEY,
  CAR_ID BIGINT NOT NULL,
  USER_ID BIGINT NOT NULL,
  RES_DATE DATE
);

ALTER TABLE RESERVATION ADD FOREIGN KEY (CAR_ID) REFERENCES CAR(CAR_ID);
ALTER TABLE RESERVATION ADD FOREIGN KEY (USER_ID) REFERENCES APIUSER(USER_ID);
CREATE INDEX IDX_RES_DATE_ ON RESERVATION(RES_DATE);
